import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/* Issue #345 — encrypted packages and document protection through the
 * real shell + worker + WASM engine.
 *
 * The fixtures are generated by `format_docx::test_fixtures` and pinned by
 * `crates/format-docx/tests/protection.rs` (regenerate with
 * `NGE_UPDATE_E2E_FIXTURES=1 cargo test -p format-docx --test protection`).
 */

const fixture = (name: string) =>
    Array.from(readFileSync(fileURLToPath(new URL(`./fixtures/${name}`, import.meta.url))));

declare global {
    interface Window {
        __dispatch: (cmd: unknown) => Promise<any>;
        __paintIdle?: boolean;
    }
}

async function boot(page: import('@playwright/test').Page) {
    await page.goto('/');
    await page.waitForFunction(() => window.__paintIdle === true, undefined, {
        timeout: 20_000,
    });
}

test('an encrypted package is refused with the typed EncryptedDocument error', async ({
    page,
}) => {
    test.setTimeout(30_000);
    await boot(page);
    const evt = await page.evaluate(
        async (arr: number[]) =>
            window.__dispatch({
                type: 'OPEN_DOCUMENT',
                bytes: new Uint8Array(arr),
                format: 'docx',
                name: 'locked.docx',
            }),
        fixture('encrypted_stub.docx'),
    );
    expect(evt.type).toBe('ERROR');
    expect(evt.kind).toBe('EncryptedDocument');
    expect(String(evt.message).toLowerCase()).not.toContain('zip');
    await expect(page.locator('.nge-fm__error')).toContainText('encrypted with a password');
    /* The worker never trapped. */
    await expect(page.locator('.nge-trap')).toHaveCount(0);
});
