import { test, expect, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { boot, burst, documentText, settle } from './helpers/editor';

/* Issue #345 — encrypted packages and document protection through the
 * real shell + worker + WASM engine.
 *
 * The fixtures are generated by `format_docx::test_fixtures` and pinned by
 * `crates/format-docx/tests/protection.rs` (regenerate with
 * `NGE_UPDATE_E2E_FIXTURES=1 cargo test -p format-docx --test protection`):
 *
 * - `encrypted_stub.docx` — an OLE compound file with the MS-OFFCRYPTO
 *   `EncryptionInfo` / `EncryptedPackage` streams;
 * - `forms_protected.docx` — `<w:documentProtection w:edit="forms"
 *   w:enforcement="1"/>` over: 0 protected text, 1 `Name: ` + a run-level
 *   content control (`Your name here`, bytes [6, 20)) + `.`, 2 `City: ` +
 *   a FORMTEXT field (five EN SPACEs, bytes [6, 21)), 3 a block-level
 *   content control, 4 protected text.
 *
 * Typing goes through the real hidden textarea (`burst` → `beforeinput`
 * → HiddenInput → INSERT_TEXT), the caret is placed with SET_SELECTION.
 */

const fixture = (name: string) =>
    Array.from(readFileSync(fileURLToPath(new URL(`./fixtures/${name}`, import.meta.url))));

declare global {
    interface Window {
        __dispatch: (cmd: unknown) => Promise<any>;
        __paintIdle?: boolean;
    }
}

const pos = (block: number, offset: number) => ({
    path: { steps: [{ kind: 'BLOCK', idx: block }] },
    offset,
});

async function select(page: Page, from: [number, number], to: [number, number]) {
    const evt = await page.evaluate(
        ({ start, end }) =>
            window.__dispatch({ type: 'SET_SELECTION', range: { start, end }, caret: end }),
        { start: pos(...from), end: pos(...to) },
    );
    expect(evt.type).toBe('SELECTION_CHANGED');
}

async function openFixture(page: Page, name: string) {
    return page.evaluate(
        async ({ arr, name }) =>
            window.__dispatch({
                type: 'OPEN_DOCUMENT',
                bytes: new Uint8Array(arr),
                format: 'docx',
                name,
            }),
        { arr: fixture(name), name },
    );
}

test('an encrypted package is refused with the typed EncryptedDocument error', async ({
    page,
}) => {
    test.setTimeout(30_000);
    await boot(page);
    const evt = await openFixture(page, 'encrypted_stub.docx');
    expect(evt.type).toBe('ERROR');
    expect(evt.kind).toBe('EncryptedDocument');
    expect(String(evt.message).toLowerCase()).not.toContain('zip');
    await expect(page.locator('.nge-fm__error')).toContainText('encrypted with a password');
    /* The worker never trapped. */
    await expect(page.locator('.nge-trap')).toHaveCount(0);
});

test('forms protection: typing outside a field is refused, inside it lands', async ({
    page,
}) => {
    test.setTimeout(45_000);
    await boot(page);
    const loaded = await openFixture(page, 'forms_protected.docx');
    expect(loaded.type).toBe('DOCUMENT_LOADED');
    await select(page, [0, 0], [0, 0]);
    await expect(page.locator('.nge-protection')).toContainText('Filling in forms');
    /* Track Changes / Accept / Reject are locked by the protection. */
    await expect(page.getByRole('button', { name: 'Track changes' })).toBeDisabled();
    await expect(page.getByRole('button', { name: 'Accept all revisions' })).toBeDisabled();

    const before = await documentText(page);
    expect(before).toContain('Please fill in the form below.');

    /* Outside every field: refused with the typed error, toasted, and
       nothing changes. */
    await select(page, [0, 6], [0, 6]);
    await burst(page, ['!']);
    await settle(page);
    await expect(page.locator('.nge-toast__message')).toContainText(
        'This document is protected (filling in forms): only form fields and content controls can be edited',
    );
    await expect(page.locator('.nge-fm__error')).toHaveCount(0);
    expect(await documentText(page)).toBe(before);
    const refused = await page.evaluate(async () => {
        await window.__dispatch({
            type: 'SET_SELECTION',
            range: {
                start: { path: { steps: [{ kind: 'BLOCK', idx: 4 }] }, offset: 0 },
                end: { path: { steps: [{ kind: 'BLOCK', idx: 4 }] }, offset: 0 },
            },
            caret: { path: { steps: [{ kind: 'BLOCK', idx: 4 }] }, offset: 0 },
        });
        return window.__dispatch({ type: 'INSERT_TEXT', text: 'x' });
    });
    expect(refused.type).toBe('ERROR');
    expect(refused.kind).toBe('Protected');

    /* Inside the run-level content control (at its closer). */
    await select(page, [1, 20], [1, 20]);
    await burst(page, ['!', '?']);
    let text = await documentText(page);
    expect(text).toContain('Name: Your name here!?.');

    /* The legacy text form field: select it whole (what a click does),
       then type — the field keeps its result. */
    await select(page, [2, 6], [2, 21]);
    await burst(page, ['C', 'a', 'i', 'r', 'o']);
    text = await documentText(page);
    expect(text).toContain('City: Cairo');

    /* The block-level content control takes typing and Enter. */
    await select(page, [3, 14], [3, 14]);
    await burst(page, [' More.', 'ENTER', 'Line two.']);
    text = await documentText(page);
    expect(text).toContain('Notes go here. More.');
    expect(text).toContain('Line two.');
    expect(text).toContain('Please fill in the form below.');
    expect(text).toContain('Signature (office use only).');
    await expect(page.locator('.nge-trap')).toHaveCount(0);
});
