import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/* Issue #221 — `OPEN_DOCUMENT.defaults.page_size` reaches
 * `format_docx::read_docx_with_settings` end to end through the REAL
 * shell + worker + WASM engine, not just the native `Engine::apply_sync`
 * bridge tests in `crates/engine-wasm/src/lib.rs`.
 *
 * `no_pgsz.docx` (generated by `.agent-scratch/make_no_pgsz_fixture.py`,
 * pinned readable from the Rust side by
 * `ts_e2e_no_pgsz_fixture_is_a_valid_pgsz_less_package` in
 * `crates/format-docx/src/opc/archive.rs`) has a `<w:sectPr/>` with no
 * `<w:pgSz>` at all — deliberately NOT one of the
 * `crates/format-docx/tests/fixtures/*.docx` corpus fixtures, every one of
 * which issue #109 pinned an explicit `<w:pgSz>` onto so
 * `tools/roundtrip --fixtures` never silently exercises this fallback path.
 *
 * Assertions ride the `SET_SELECTION` reply's `section_geometry.height_pt`
 * — engine truth, valid under headless Chrome (see CLAUDE.md: the
 * interactive canvas itself is never screenshotted here). US Letter is
 * 792 pt tall; A4 (the crate default, and what this file would lay out at
 * without `defaults`) is ~841.9 pt.
 */

const FIXTURE = fileURLToPath(new URL('./fixtures/no_pgsz.docx', import.meta.url));

declare global {
    interface Window {
        __dispatch: (cmd: unknown) => Promise<any>;
        __paintIdle?: boolean;
    }
}

test('OPEN_DOCUMENT defaults.page_size = Letter lays out a pgSz-less fixture at Letter height', async ({
    page,
}) => {
    test.setTimeout(30_000);
    await page.goto('/');
    await page.waitForFunction(() => window.__paintIdle === true, undefined, {
        timeout: 20_000,
    });

    const bytes = Array.from(readFileSync(FIXTURE));

    const result = await page.evaluate(async (arr: number[]) => {
        const dispatch = (cmd: unknown): Promise<any> => window.__dispatch(cmd);
        const top = (idx: number, offset: number) => ({
            path: { steps: [{ kind: 'BLOCK', idx }] },
            offset,
        });

        const loaded = await dispatch({
            type: 'OPEN_DOCUMENT',
            bytes: new Uint8Array(arr),
            format: 'docx',
            name: 'no_pgsz.docx',
            defaults: { page_size: 'Letter', widow_control: undefined },
        });
        if (loaded.type === 'ERROR') throw new Error(loaded.message);

        const sel = await dispatch({
            type: 'SET_SELECTION',
            range: { start: top(0, 0), end: top(0, 0) },
            caret: top(0, 0),
        });
        return { loadedType: loaded.type, heightPt: sel.section_geometry?.height_pt as number };
    }, bytes);

    expect(result.loadedType).toBe('DOCUMENT_LOADED');
    /* US Letter (12240 twips / 20) — not A4's ~841.9 pt. */
    expect(result.heightPt).toBeCloseTo(792.0, 1);
});
