/**
 * @nge/core — public type surface.
 *
 * Re-exports the bridge Command/Event union types generated by tsify-next
 * from `crates/bridge`. The wasm-pack output lives at
 * `crates/engine-wasm/pkg/engine_wasm.js`; the relative path crosses the
 * pnpm workspace boundary but is stable because the monorepo root is a
 * single git tree.
 *
 * Downstream UI never imports from `crates/engine-wasm/pkg` directly — the
 * SDK boundary owns that coupling.
 */
export type {
    Command,
    Event,
    DocFormat,
    DocumentDefaults,
    DefaultPageSize,
    ErrorKind,
    PackageLimitsOverride,
    TextAttrsPatch,
    UnderlineStyle,
    VerticalScript,
    FormattingToggle,
    FontSlot,
    Alignment,
    Direction,
    PdfConformance,
    ImageFit,
    ImageBlob,
    SelectionModifier,
    MoveDirection,
    BridgeBorderStyle,
    BridgeCellBorders,
    BridgeBorderStroke,
    TablePropertiesPatch,
    InsertSide,
    PageOrientation,
    SectionBreakKind,
    HeaderFooterArea,
    BridgeStoryRef,
    BridgeFieldRef,
    BridgeHfRole,
    FieldKind,
    TocSwitches,
    ListKind,
    LogicalPos,
    LogicalRange,
    BlockPath,
    PathStep,
    SelectionKind,
    Rect,
    Point,
    ImageRect,
    ImageWrapMode,
    TextBoxHop,
    Color,
    Script,
    TextAttrs,
    AttrsMixed,
    EngineStats,
    LayoutDegraded,
    LayoutDegradeReason,
    EngineCapabilities,
    A11yTree,
    A11yPatch,
    A11yTextBox,
    A11yNote,
    A11yNoteKind,
    A11yNoteRef,
    A11yObjectKind,
    A11yObjectRef,
    AnnouncementPriority,
    BridgeSectionGeometry,
    BridgeCellProperties,
    BridgeParaPropertiesPatch,
    BridgeSpanStylePatch,
    BridgeStyleProperties,
    BridgeTabStop,
    BridgeTabKind,
    BridgeTabLeader,
    BridgeIndent,
    RendererDowngrade,
    RendererDowngradeReason,
} from '../../../crates/engine-wasm/pkg/engine_wasm.js';

import type {
    BlockPath,
    Command,
    Event,
    RendererDowngrade,
} from '../../../crates/engine-wasm/pkg/engine_wasm.js';

/**
 * The minimum contract @nge/core depends on. The concrete EngineClient
 * (worker spawn, RPC, crash recovery) currently lives in `ts/src/engine/`
 * and will migrate into this package in a follow-up. Any implementation
 * matching this shape can be passed to `EngineProvider`.
 */
export interface EngineClientLike {
    dispatch(cmd: Command, transfer?: Transferable[]): Promise<Event>;
    subscribe(fn: (e: Event) => void): () => void;
    init(canvas: OffscreenCanvas): Promise<void>;
    recover(canvas: OffscreenCanvas): Promise<void>;
    readonly crossOriginIsolated: boolean;
    readonly renderer: string;
    /**
     * Issue #240 — optional crash-loop renderer policy. The downgrade in
     * force (set at boot from a persisted streak, or by a recovery), a
     * change feed for it, and the "retry the GPU renderer" action (forgets
     * the persisted streak and probes the GPU again). Issue #270 — the
     * retry must keep the document: the reference client restarts its
     * engine in place (a recovery generation without a trap), never a
     * page reload. Implementations without a GPU policy omit all three;
     * the Dev HUD then shows no retry action.
     */
    readonly rendererDowngrade?: RendererDowngrade | undefined;
    onRendererDowngrade?(fn: (d: RendererDowngrade | undefined) => void): () => void;
    retryGpuRenderer?(): Promise<void>;
    /**
     * Issue #330 - optional in-place engine restart for the crash overlay:
     * `restartInPlace` re-spawns the engine from the event log (joining a
     * recovery already under way), `prepareCarryOver` makes the next page
     * reload carry the document. A page reload without it starts a new
     * session and clears the log, so the overlay offers these buttons
     * only when the client supplies them.
     */
    /**
     * Issue #333 - optional checkpoint health: whether the worker's
     * snapshot writes are landing. `failing` is set once the bounded
     * retries of a failed write are exhausted (the replay tail is then
     * growing) and cleared by the next successful write. The recovery
     * banner turns it into a "save your work" warning.
     */
    readonly checkpointStatus?: CheckpointStatus;
    onCheckpointStatus?(fn: (s: CheckpointStatus) => void): () => void;
    /**
     * Issue #388 - optional previous-session recovery. A page reload
     * starts a new session; when the previous generation ended with
     * unsaved edits, the client sets that session aside instead of
     * dropping it and reports it here until the user decides:
     * `recoverPreviousSession` swaps it in (the engine restarts from it),
     * `discardPreviousSession` throws it away. `hasUnsavedChanges` is the
     * synchronous answer a `beforeunload` guard needs.
     */
    readonly previousSession?: PreviousSessionInfo | undefined;
    onPreviousSession?(fn: (p: PreviousSessionInfo | undefined) => void): () => void;
    recoverPreviousSession?(): Promise<void>;
    discardPreviousSession?(): Promise<void>;
    readonly hasUnsavedChanges?: boolean;
    restartInPlace?(): Promise<void>;
    prepareCarryOver?(): Promise<void>;
    /**
     * Issue #315 — optional crash-recovery report. The outcome of the most
     * recent recovery (`undefined` before any), and a feed that fires once
     * per completed recovery with its final report. Implementations
     * without crash recovery omit both; the recovery banner and the Dev
     * HUD's recovery rows then never show.
     */
    readonly lastRecovery?: RecoveryReport | undefined;
    onRecovery?(fn: (report: RecoveryReport) => void): () => void;
}

/** Issue #388 - see `EngineClientLike.previousSession`. */
export interface PreviousSessionInfo {
    /** When the session was set aside (ms since the epoch). */
    archivedAt: number;
    /** When its last edit was journaled, when known. */
    lastEditAt: number | undefined;
    /** Journaled commands it holds. */
    commandCount: number;
}

/** Issue #333 - see `EngineClientLike.checkpointStatus`. */
export interface CheckpointStatus {
    failing: boolean;
    /** Consecutive failed snapshot writes in the current run. */
    failures: number;
}

/**
 * Issue #315 — what a crash recovery achieved and what it had to give up
 * (#85 / #241 / #268 / #99). The concrete `EngineClient`'s `RecoveryInfo`
 * satisfies it structurally. Turn it into user-facing notices with
 * `recoveryNotices()`; an empty list means a normal recovery, which stays
 * silent.
 */
export interface RecoveryReport {
    /** A persisted base snapshot was restored before the tail replay. */
    restored: boolean;
    /** Replay-tail commands applied on top of the base. */
    appliedCommands: number;
    /** The renderer the recovered engine paints with. */
    renderer: string;
    /** The crash-loop downgrade in force for the recovered generation. */
    rendererDowngrade: RendererDowngrade | undefined;
    /** THIS recovery tripped the downgrade (later recoveries re-send it). */
    rendererDowngraded: boolean;
    /** Newer snapshots skipped because they would not restore. */
    snapshotFallbacks: number;
    /** Nothing restored and the log was pruned: the document is lost. */
    logTruncated: boolean;
    /** Readable snapshots passed over for an older base with its package. */
    packageFallbacks: number;
    /** The source package could not be re-attached: saving writes a
     *  minimal document without the original file's sibling parts. */
    packageLost: boolean;
    /** The restored base is the document's pinned snapshot. */
    pinnedBase: boolean;
    /** That pinned base came back WITHOUT its tail: later edits are lost. */
    tailDropped: boolean;
    /** When the restored base snapshot was taken (ms since the epoch). */
    baseSnapshotAt: number | undefined;
    /** Issue #270 — why the recovery ran: a worker `trap`, or an in-place
     *  `renderer-retry` (a planned respawn, no crash). Absent = `trap`. */
    cause?: 'trap' | 'renderer-retry' | 'engine-reload' | 'page-reload' | 'session-restore';
}

/** Read-only revision row consumed by the Track Changes sidebar. */
export interface RevisionSnapshot {
    block: number;
    start: number;
    end: number;
    /** Issue #247 — `move-from` / `move-to` are the two halves of a
     *  tracked move; `format` a tracked formatting change. */
    kind: 'insert' | 'delete' | 'format' | 'move-from' | 'move-to';
    author: string;
    date: string;
    /** Issue #247 — the move's range name; both halves share it. */
    move_name?: string;
    /** Issue #262 — a paragraph-MARK revision (a tracked paragraph split
     *  or merge), addressed by the empty range at the paragraph end. */
    mark?: boolean;
    /** Issue #304 — the revision's stable id: unique per row, unchanged
     *  by edits elsewhere (two wrappers over one range are two ids).
     *  Pass it to `acceptRevision` / `rejectRevision`. Optional so
     *  engines that pre-date it still satisfy the contract. */
    revision_id?: number;
}

/** Read-only comment row consumed by the Comments rail. Sprint 7
 *  added the `resolved` flag (in-memory only — no
 *  `commentsExtended.xml` round-trip yet). */
export interface CommentSnapshot {
    id: number;
    author: string;
    date: string;
    text: string;
    /** The LAST block index of the start path — flat, kept for
     *  compatibility; for a comment inside a table cell it is the cell
     *  paragraph's index, not a top-level block. Use `start_path`. */
    start_block: number;
    start_offset: number;
    end_block: number;
    end_offset: number;
    /** Issue #254 — the full anchor paths (a comment inside a table cell
     *  is `[BLOCK t, CELL r/c, BLOCK i]`), ready for a `SET_SELECTION`
     *  `LogicalPos`. Optional — implementations that pre-date #254 omit
     *  them (consumers then fall back to the flat index). */
    start_path?: BlockPath;
    end_path?: BlockPath;
    /** Optional — implementations that pre-date Sprint 7 omit it. */
    resolved?: boolean;
    /** Issue #27 — parent comment `w:id` when this row is a threaded
     *  reply; `undefined` (or absent) on top-level comments. Round-
     *  trips through `word/commentsExtended.xml`
     *  `<w15:commentEx w15:paraIdParent>`. */
    parent_id?: number;
}

/**
 * Optional surface for engines that ship read-only snapshots
 * (revisions + comments). Implementations that do not surface these
 * may omit the methods; the matching UI components degrade to "no data".
 */
export interface EngineClientSnapshots {
    revisionsSnapshot?(): Promise<RevisionSnapshot[]>;
    commentsSnapshot?(): Promise<CommentSnapshot[]>;
}
