/**
 * @nge/core — public type surface.
 *
 * Re-exports the bridge Command/Event union types generated by tsify-next
 * from `crates/bridge`. The wasm-pack output lives at
 * `crates/engine-wasm/pkg/engine_wasm.js`; the relative path crosses the
 * pnpm workspace boundary but is stable because the monorepo root is a
 * single git tree.
 *
 * Downstream UI never imports from `crates/engine-wasm/pkg` directly — the
 * SDK boundary owns that coupling.
 */
export type {
    Command,
    Event,
    DocFormat,
    TextAttrsPatch,
    UnderlineStyle,
    VerticalScript,
    Alignment,
    Direction,
    PdfConformance,
    ImageFit,
    ImageBlob,
    SelectionModifier,
    MoveDirection,
    BridgeBorderStyle,
    BridgeCellBorders,
    BridgeBorderStroke,
    InsertSide,
    PageOrientation,
    ListKind,
    LogicalPos,
    LogicalRange,
    BlockPath,
    PathStep,
    SelectionKind,
    Rect,
    Point,
    Color,
    Script,
    TextAttrs,
    AttrsMixed,
    EngineStats,
    EngineCapabilities,
    A11yTree,
    A11yPatch,
    AnnouncementPriority,
    BridgeSectionGeometry,
    BridgeCellProperties,
    BridgeTabStop,
    BridgeTabKind,
    BridgeIndent,
} from '../../../crates/engine-wasm/pkg/engine_wasm.js';

import type {
    Command,
    Event,
} from '../../../crates/engine-wasm/pkg/engine_wasm.js';

/**
 * The minimum contract @nge/core depends on. The concrete EngineClient
 * (worker spawn, RPC, crash recovery) currently lives in `ts/src/engine/`
 * and will migrate into this package in a follow-up. Any implementation
 * matching this shape can be passed to `EngineProvider`.
 */
export interface EngineClientLike {
    dispatch(cmd: Command, transfer?: Transferable[]): Promise<Event>;
    subscribe(fn: (e: Event) => void): () => void;
    init(canvas: OffscreenCanvas): Promise<void>;
    recover(canvas: OffscreenCanvas): Promise<void>;
    readonly crossOriginIsolated: boolean;
    readonly renderer: string;
}

/** Read-only revision row consumed by the Track Changes sidebar. */
export interface RevisionSnapshot {
    block: number;
    start: number;
    end: number;
    kind: 'insert' | 'delete';
    author: string;
    date: string;
}

/** Read-only comment row consumed by the Comments rail. Sprint 7
 *  added the `resolved` flag (in-memory only — no
 *  `commentsExtended.xml` round-trip yet). */
export interface CommentSnapshot {
    id: number;
    author: string;
    date: string;
    text: string;
    start_block: number;
    start_offset: number;
    end_block: number;
    end_offset: number;
    /** Optional — implementations that pre-date Sprint 7 omit it. */
    resolved?: boolean;
    /** Issue #27 — parent comment `w:id` when this row is a threaded
     *  reply; `undefined` (or absent) on top-level comments. Round-
     *  trips through `word/commentsExtended.xml`
     *  `<w15:commentEx w15:paraIdParent>`. */
    parent_id?: number;
}

/**
 * Optional surface for engines that ship read-only snapshots
 * (revisions + comments). Implementations that do not surface these
 * may omit the methods; the matching UI components degrade to "no data".
 */
export interface EngineClientSnapshots {
    revisionsSnapshot?(): Promise<RevisionSnapshot[]>;
    commentsSnapshot?(): Promise<CommentSnapshot[]>;
}
