/* Phase 4 §4 — single import site for the bridge schema.
 *
 * The `Command`/`Event` types are generated by `tsify-next` into the
 * `engine-wasm` wasm-pack package (the `bridge` crate is not built
 * standalone). Re-exporting them here keeps the deep `../../../crates/...`
 * relative path in one place — UI code imports from `../engine/types`. */
export type {
    A11yParagraph,
    A11yRun,
    A11yTree,
    ClientCapabilities,
    Color,
    Command,
    Direction,
    DocFormat,
    EngineCapabilities,
    EngineStats,
    Event,
    FontMetrics,
    ImageBlob,
    ImageFit,
    LogicalPos,
    LogicalRange,
    ParagraphId,
    PdfConformance,
    Point,
    Rect,
    Script,
    SelectionModifier,
    TextAttrs,
    TextAttrsPatch,
    UnderlineStyle,
    VerticalScript,
} from '../../../crates/engine-wasm/pkg/engine_wasm.js';
